name: Pylint

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        sudo apt install python3-poetry
        poetry install
        mkdir keys
        touch cache.txt
        poetry run python keyboxer.py

    - name: Upload a Build Artifact 
      uses: actions/upload-artifact@v4
      with:
        path: .
